export type Officer = {
  id: string;
  name: string;
  war: number;
  int: number;
  command: number;
  role: string;
  specialty: '统帅' | '勇将' | '谋士' | '内政';
  faction: 'wei' | 'shu' | 'wu';
  portraitIndex: number;
};
export const ROSTERS: Record<'wei' | 'shu' | 'wu', Officer[]> = {
  wei: [
    {
      id: 'cao',
      name: '曹操',
      war: 86,
      int: 91,
      command: 96,
      role: '雄才大略',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 0,
    },
    {
      id: 'xiahou',
      name: '夏侯惇',
      war: 90,
      int: 63,
      command: 85,
      role: '陷阵先锋',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 1,
    },
    {
      id: 'zhangliao',
      name: '张辽',
      war: 94,
      int: 78,
      command: 95,
      role: '威震逍遥津',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 2,
    },
    {
      id: 'xunyu',
      name: '荀彧',
      war: 42,
      int: 98,
      command: 68,
      role: '王佐之才',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 3,
    },
    {
      id: 'xuchu',
      name: '许褚',
      war: 94,
      int: 41,
      command: 72,
      role: '虎卫突阵',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 4,
    },
    {
      id: 'dianwei',
      name: '典韦',
      war: 96,
      int: 37,
      command: 69,
      role: '帐前死士',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 5,
    },
    {
      id: 'xiahouyuan',
      name: '夏侯渊',
      war: 90,
      int: 69,
      command: 90,
      role: '疾行奇袭',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 6,
    },
    {
      id: 'xuhuang',
      name: '徐晃',
      war: 91,
      int: 74,
      command: 91,
      role: '长驱破阵',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 7,
    },
    {
      id: 'zhanghe',
      name: '张郃',
      war: 90,
      int: 79,
      command: 90,
      role: '巧变统军',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 8,
    },
    {
      id: 'lejin',
      name: '乐进',
      war: 87,
      int: 64,
      command: 80,
      role: '先登夺城',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 9,
    },
    {
      id: 'lidian',
      name: '李典',
      war: 81,
      int: 84,
      command: 81,
      role: '审势辅军',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 10,
    },
    {
      id: 'yujin',
      name: '于禁',
      war: 82,
      int: 77,
      command: 85,
      role: '持重治军',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 11,
    },
    {
      id: 'caoren',
      name: '曹仁',
      war: 86,
      int: 81,
      command: 92,
      role: '坚城镇守',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 12,
    },
    {
      id: 'guojia',
      name: '郭嘉',
      war: 37,
      int: 97,
      command: 64,
      role: '奇谋决胜',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 13,
    },
    {
      id: 'simayi',
      name: '司马懿',
      war: 57,
      int: 96,
      command: 97,
      role: '深谋统军',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 14,
    },
    {
      id: 'jiaxu',
      name: '贾诩',
      war: 33,
      int: 96,
      command: 70,
      role: '料敌设谋',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 15,
    },
    {
      id: 'caopi',
      name: '曹丕',
      war: 71,
      int: 84,
      command: 80,
      role: '文治开国',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 16,
    },
    {
      id: 'caozhi',
      name: '曹植',
      war: 31,
      int: 90,
      command: 39,
      role: '才高八斗',
      specialty: '内政',
      faction: 'wei',
      portraitIndex: 17,
    },
    {
      id: 'caohong',
      name: '曹洪',
      war: 82,
      int: 55,
      command: 77,
      role: '骁勇护主',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 18,
    },
    {
      id: 'caochun',
      name: '曹纯',
      war: 85,
      int: 66,
      command: 86,
      role: '虎豹骑督',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 19,
    },
    {
      id: 'caoxiu',
      name: '曹休',
      war: 81,
      int: 73,
      command: 84,
      role: '千里良驹',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 20,
    },
    {
      id: 'caozhen',
      name: '曹真',
      war: 82,
      int: 75,
      command: 89,
      role: '西陲统军',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 21,
    },
    {
      id: 'xiahoushang',
      name: '夏侯尚',
      war: 76,
      int: 77,
      command: 82,
      role: '征南督军',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 22,
    },
    {
      id: 'manchong',
      name: '满宠',
      war: 59,
      int: 89,
      command: 84,
      role: '坚壁御敌',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 23,
    },
    {
      id: 'chengyu',
      name: '程昱',
      war: 54,
      int: 94,
      command: 74,
      role: '谋定后动',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 24,
    },
    {
      id: 'xunyou',
      name: '荀攸',
      war: 27,
      int: 96,
      command: 73,
      role: '奇策十二',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 25,
    },
    {
      id: 'chenqun',
      name: '陈群',
      war: 22,
      int: 90,
      command: 36,
      role: '九品贤臣',
      specialty: '内政',
      faction: 'wei',
      portraitIndex: 26,
    },
    {
      id: 'zhongyao',
      name: '钟繇',
      war: 24,
      int: 87,
      command: 40,
      role: '德望重臣',
      specialty: '内政',
      faction: 'wei',
      portraitIndex: 27,
    },
    {
      id: 'dengai',
      name: '邓艾',
      war: 83,
      int: 91,
      command: 94,
      role: '奇袭阴平',
      specialty: '统帅',
      faction: 'wei',
      portraitIndex: 28,
    },
    {
      id: 'zhonghui',
      name: '钟会',
      war: 55,
      int: 94,
      command: 88,
      role: '谋略纵横',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 29,
    },
    {
      id: 'wangshuang',
      name: '王双',
      war: 87,
      int: 37,
      command: 66,
      role: '重斧猛将',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 30,
    },
    {
      id: 'wenping',
      name: '文聘',
      war: 85,
      int: 72,
      command: 87,
      role: '江汉磐石',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 31,
    },
    {
      id: 'zangba',
      name: '臧霸',
      war: 80,
      int: 63,
      command: 81,
      role: '泰山宿将',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 32,
    },
    {
      id: 'pangde',
      name: '庞德',
      war: 94,
      int: 69,
      command: 85,
      role: '白马骁将',
      specialty: '勇将',
      faction: 'wei',
      portraitIndex: 33,
    },
    {
      id: 'simashi',
      name: '司马师',
      war: 69,
      int: 90,
      command: 87,
      role: '沉毅经略',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 34,
    },
    {
      id: 'simazhao',
      name: '司马昭',
      war: 62,
      int: 88,
      command: 81,
      role: '持重谋国',
      specialty: '谋士',
      faction: 'wei',
      portraitIndex: 35,
    },
  ],
  shu: [
    {
      id: 'liu',
      name: '刘备',
      war: 78,
      int: 80,
      command: 88,
      role: '仁德之主',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 0,
    },
    {
      id: 'guan',
      name: '关羽',
      war: 98,
      int: 76,
      command: 94,
      role: '万人之敌',
      specialty: '统帅',
      faction: 'shu',
      portraitIndex: 1,
    },
    {
      id: 'zhang',
      name: '张飞',
      war: 99,
      int: 45,
      command: 88,
      role: '勇冠三军',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 2,
    },
    {
      id: 'zhuge',
      name: '诸葛亮',
      war: 38,
      int: 99,
      command: 95,
      role: '卧龙军师',
      specialty: '统帅',
      faction: 'shu',
      portraitIndex: 3,
    },
    {
      id: 'zhaoyun',
      name: '赵云',
      war: 96,
      int: 81,
      command: 94,
      role: '长枪突阵',
      specialty: '统帅',
      faction: 'shu',
      portraitIndex: 4,
    },
    {
      id: 'huangzhong',
      name: '黄忠',
      war: 93,
      int: 66,
      command: 87,
      role: '神射破敌',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 5,
    },
    {
      id: 'machao',
      name: '马超',
      war: 95,
      int: 60,
      command: 88,
      role: '铁骑冲阵',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 6,
    },
    {
      id: 'weiyan',
      name: '魏延',
      war: 91,
      int: 72,
      command: 88,
      role: '奇袭先锋',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 7,
    },
    {
      id: 'jiangwei',
      name: '姜维',
      war: 88,
      int: 91,
      command: 91,
      role: '文武统军',
      specialty: '统帅',
      faction: 'shu',
      portraitIndex: 8,
    },
    {
      id: 'pangtong',
      name: '庞统',
      war: 36,
      int: 97,
      command: 82,
      role: '连环奇谋',
      specialty: '谋士',
      faction: 'shu',
      portraitIndex: 9,
    },
    {
      id: 'fazheng',
      name: '法正',
      war: 42,
      int: 95,
      command: 80,
      role: '奇策辅军',
      specialty: '谋士',
      faction: 'shu',
      portraitIndex: 10,
    },
    {
      id: 'xushu',
      name: '徐庶',
      war: 59,
      int: 94,
      command: 79,
      role: '料敌谋士',
      specialty: '谋士',
      faction: 'shu',
      portraitIndex: 11,
    },
    {
      id: 'maliang',
      name: '马良',
      war: 32,
      int: 91,
      command: 61,
      role: '内政贤才',
      specialty: '谋士',
      faction: 'shu',
      portraitIndex: 12,
    },
    {
      id: 'guanping',
      name: '关平',
      war: 85,
      int: 66,
      command: 77,
      role: '青龙先锋',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 13,
    },
    {
      id: 'zhoucang',
      name: '周仓',
      war: 86,
      int: 43,
      command: 63,
      role: '持刀猛士',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 14,
    },
    {
      id: 'madai',
      name: '马岱',
      war: 86,
      int: 74,
      command: 80,
      role: '稳健副将',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 15,
    },
    {
      id: 'liushan',
      name: '刘禅',
      war: 26,
      int: 58,
      command: 41,
      role: '宽仁守成',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 16,
    },
    {
      id: 'guanxing',
      name: '关兴',
      war: 88,
      int: 67,
      command: 78,
      role: '青龙继志',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 17,
    },
    {
      id: 'zhangbao',
      name: '张苞',
      war: 89,
      int: 53,
      command: 76,
      role: '燕人后继',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 18,
    },
    {
      id: 'zhangyi',
      name: '张翼',
      war: 77,
      int: 72,
      command: 81,
      role: '南征宿将',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 19,
    },
    {
      id: 'wangping',
      name: '王平',
      war: 77,
      int: 78,
      command: 87,
      role: '无当飞军',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 20,
    },
    {
      id: 'liaohua',
      name: '廖化',
      war: 77,
      int: 68,
      command: 77,
      role: '历战先锋',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 21,
    },
    {
      id: 'zhangni',
      name: '张嶷',
      war: 76,
      int: 76,
      command: 82,
      role: '安南良将',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 22,
    },
    {
      id: 'wuyi',
      name: '吴懿',
      war: 77,
      int: 71,
      command: 83,
      role: '汉中督军',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 23,
    },
    {
      id: 'liyan',
      name: '李严',
      war: 77,
      int: 82,
      command: 82,
      role: '才干治军',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 24,
    },
    {
      id: 'yanyan',
      name: '严颜',
      war: 84,
      int: 70,
      command: 81,
      role: '巴蜀老将',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 25,
    },
    {
      id: 'menghuo',
      name: '孟获',
      war: 90,
      int: 51,
      command: 77,
      role: '南中雄主',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 26,
    },
    {
      id: 'zhurong',
      name: '祝融',
      war: 88,
      int: 59,
      command: 72,
      role: '飞刃逐猎',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 27,
    },
    {
      id: 'huangyueying',
      name: '黄月英',
      war: 44,
      int: 95,
      command: 48,
      role: '巧思善工',
      specialty: '内政',
      faction: 'shu',
      portraitIndex: 28,
    },
    {
      id: 'sunshangxiang',
      name: '孙尚香',
      war: 86,
      int: 70,
      command: 74,
      role: '弓腰姬将',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 29,
    },
    {
      id: 'baosanniang',
      name: '鲍三娘',
      war: 83,
      int: 58,
      command: 67,
      role: '凤舞战阵',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 30,
    },
    {
      id: 'guanyinping',
      name: '关银屏',
      war: 87,
      int: 61,
      command: 72,
      role: '虎女青锋',
      specialty: '勇将',
      faction: 'shu',
      portraitIndex: 31,
    },
    {
      id: 'mizhu',
      name: '糜竺',
      war: 23,
      int: 85,
      command: 38,
      role: '富商辅汉',
      specialty: '内政',
      faction: 'shu',
      portraitIndex: 32,
    },
    {
      id: 'jianyong',
      name: '简雍',
      war: 27,
      int: 82,
      command: 34,
      role: '谈笑折冲',
      specialty: '内政',
      faction: 'shu',
      portraitIndex: 33,
    },
    {
      id: 'sunqian',
      name: '孙乾',
      war: 26,
      int: 84,
      command: 35,
      role: '辩才安邦',
      specialty: '内政',
      faction: 'shu',
      portraitIndex: 34,
    },
    {
      id: 'feiyi',
      name: '费祎',
      war: 30,
      int: 93,
      command: 74,
      role: '经国济民',
      specialty: '谋士',
      faction: 'shu',
      portraitIndex: 35,
    },
  ],
  wu: [
    {
      id: 'sun',
      name: '孙权',
      war: 73,
      int: 87,
      command: 88,
      role: '江东之主',
      specialty: '谋士',
      faction: 'wu',
      portraitIndex: 0,
    },
    {
      id: 'zhou',
      name: '周瑜',
      war: 78,
      int: 97,
      command: 97,
      role: '江左风流',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 1,
    },
    {
      id: 'gan',
      name: '甘宁',
      war: 95,
      int: 68,
      command: 87,
      role: '锦帆游侠',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 2,
    },
    {
      id: 'taishi',
      name: '太史慈',
      war: 96,
      int: 66,
      command: 88,
      role: '忠勇无双',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 3,
    },
    {
      id: 'luxun',
      name: '陆逊',
      war: 65,
      int: 95,
      command: 96,
      role: '火计统军',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 4,
    },
    {
      id: 'lumeng',
      name: '吕蒙',
      war: 86,
      int: 87,
      command: 93,
      role: '白衣渡江',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 5,
    },
    {
      id: 'huanggai',
      name: '黄盖',
      war: 87,
      int: 66,
      command: 85,
      role: '苦肉破敌',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 6,
    },
    {
      id: 'chengpu',
      name: '程普',
      war: 85,
      int: 75,
      command: 88,
      role: '宿将统军',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 7,
    },
    {
      id: 'handang',
      name: '韩当',
      war: 85,
      int: 64,
      command: 82,
      role: '水战先锋',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 8,
    },
    {
      id: 'zhoutai',
      name: '周泰',
      war: 94,
      int: 47,
      command: 79,
      role: '铁躯护主',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 9,
    },
    {
      id: 'lingtong',
      name: '凌统',
      war: 90,
      int: 66,
      command: 81,
      role: '破围先锋',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 10,
    },
    {
      id: 'xusheng',
      name: '徐盛',
      war: 85,
      int: 77,
      command: 86,
      role: '江防筑垒',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 11,
    },
    {
      id: 'dingfeng',
      name: '丁奉',
      war: 89,
      int: 71,
      command: 85,
      role: '雪中奋兵',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 12,
    },
    {
      id: 'zhangzhao',
      name: '张昭',
      war: 30,
      int: 94,
      command: 62,
      role: '内政重臣',
      specialty: '谋士',
      faction: 'wu',
      portraitIndex: 13,
    },
    {
      id: 'lusu',
      name: '鲁肃',
      war: 52,
      int: 95,
      command: 85,
      role: '联军谋士',
      specialty: '谋士',
      faction: 'wu',
      portraitIndex: 14,
    },
    {
      id: 'zhugejin',
      name: '诸葛瑾',
      war: 43,
      int: 91,
      command: 74,
      role: '外交贤臣',
      specialty: '谋士',
      faction: 'wu',
      portraitIndex: 15,
    },
    {
      id: 'sunjian',
      name: '孙坚',
      war: 92,
      int: 77,
      command: 93,
      role: '江东猛虎',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 16,
    },
    {
      id: 'sunce',
      name: '孙策',
      war: 94,
      int: 74,
      command: 94,
      role: '江东小霸',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 17,
    },
    {
      id: 'lukang',
      name: '陆抗',
      war: 71,
      int: 90,
      command: 94,
      role: '社稷之卫',
      specialty: '统帅',
      faction: 'wu',
      portraitIndex: 18,
    },
    {
      id: 'luji',
      name: '陆绩',
      war: 20,
      int: 87,
      command: 29,
      role: '博学知理',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 19,
    },
    {
      id: 'lumao',
      name: '陆瑁',
      war: 25,
      int: 85,
      command: 31,
      role: '明理德士',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 20,
    },
    {
      id: 'zhanghong',
      name: '张纮',
      war: 22,
      int: 91,
      command: 43,
      role: '筹策江东',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 21,
    },
    {
      id: 'buzhi',
      name: '步骘',
      war: 36,
      int: 86,
      command: 75,
      role: '经略交州',
      specialty: '谋士',
      faction: 'wu',
      portraitIndex: 22,
    },
    {
      id: 'zhuhuan',
      name: '朱桓',
      war: 87,
      int: 72,
      command: 88,
      role: '奋威将军',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 23,
    },
    {
      id: 'zhuran',
      name: '朱然',
      war: 81,
      int: 76,
      command: 87,
      role: '坚守江陵',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 24,
    },
    {
      id: 'panzhang',
      name: '潘璋',
      war: 82,
      int: 57,
      command: 76,
      role: '临阵悍将',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 25,
    },
    {
      id: 'jiangqin',
      name: '蒋钦',
      war: 83,
      int: 63,
      command: 79,
      role: '轻舟突击',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 26,
    },
    {
      id: 'dongxi',
      name: '董袭',
      war: 87,
      int: 48,
      command: 75,
      role: '破浪先锋',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 27,
    },
    {
      id: 'chenwu',
      name: '陈武',
      war: 85,
      int: 52,
      command: 72,
      role: '庐江精锐',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 28,
    },
    {
      id: 'lingcao',
      name: '凌操',
      war: 85,
      int: 46,
      command: 73,
      role: '轻身先登',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 29,
    },
    {
      id: 'heqi',
      name: '贺齐',
      war: 82,
      int: 74,
      command: 84,
      role: '绮甲平乱',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 30,
    },
    {
      id: 'sunshao',
      name: '孙韶',
      war: 78,
      int: 73,
      command: 79,
      role: '镇北良将',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 31,
    },
    {
      id: 'sunhuan',
      name: '孙桓',
      war: 77,
      int: 71,
      command: 80,
      role: '江东儒将',
      specialty: '勇将',
      faction: 'wu',
      portraitIndex: 32,
    },
    {
      id: 'daqiao',
      name: '大乔',
      war: 30,
      int: 86,
      command: 42,
      role: '端雅明慧',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 33,
    },
    {
      id: 'xiaoqiao',
      name: '小乔',
      war: 32,
      int: 86,
      command: 42,
      role: '江南灵秀',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 34,
    },
    {
      id: 'bulianshi',
      name: '步练师',
      war: 24,
      int: 90,
      command: 36,
      role: '柔德辅政',
      specialty: '内政',
      faction: 'wu',
      portraitIndex: 35,
    },
  ],
};
export const ALL_OFFICERS = Object.values(ROSTERS).flat();
