export type Officer = {
  id: string;
  name: string;
  war: number;
  int: number;
  command: number;
  role: string;
  specialty: '統帥' | '勇將' | '謀士' | '內政';
  faction: 'wei' | 'shu' | 'wu';
  portraitIndex: number;
};
export const ROSTERS: Record<'wei' | 'shu' | 'wu', Officer[]> = {
  wei: [
    {
      id: 'cao',
      name: '曹操',
      war: 86,
      int: 91,
      command: 96,
      role: '雄才大略',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 0,
    },
    {
      id: 'xiahou',
      name: '夏侯惇',
      war: 90,
      int: 63,
      command: 85,
      role: '陷陣先鋒',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 1,
    },
    {
      id: 'zhangliao',
      name: '張遼',
      war: 94,
      int: 78,
      command: 95,
      role: '威震逍遙津',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 2,
    },
    {
      id: 'xunyu',
      name: '荀彧',
      war: 42,
      int: 98,
      command: 68,
      role: '王佐之才',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 3,
    },
    {
      id: 'xuchu',
      name: '許褚',
      war: 94,
      int: 41,
      command: 72,
      role: '虎衛突陣',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 4,
    },
    {
      id: 'dianwei',
      name: '典韋',
      war: 96,
      int: 37,
      command: 69,
      role: '帳前死士',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 5,
    },
    {
      id: 'xiahouyuan',
      name: '夏侯淵',
      war: 90,
      int: 69,
      command: 90,
      role: '疾行奇襲',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 6,
    },
    {
      id: 'xuhuang',
      name: '徐晃',
      war: 91,
      int: 74,
      command: 91,
      role: '長驅破陣',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 7,
    },
    {
      id: 'zhanghe',
      name: '張郃',
      war: 90,
      int: 79,
      command: 90,
      role: '巧變統軍',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 8,
    },
    {
      id: 'lejin',
      name: '樂進',
      war: 87,
      int: 64,
      command: 80,
      role: '先登奪城',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 9,
    },
    {
      id: 'lidian',
      name: '李典',
      war: 81,
      int: 84,
      command: 81,
      role: '審勢輔軍',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 10,
    },
    {
      id: 'yujin',
      name: '于禁',
      war: 82,
      int: 77,
      command: 85,
      role: '持重治軍',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 11,
    },
    {
      id: 'caoren',
      name: '曹仁',
      war: 86,
      int: 81,
      command: 92,
      role: '堅城鎮守',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 12,
    },
    {
      id: 'guojia',
      name: '郭嘉',
      war: 37,
      int: 97,
      command: 64,
      role: '奇謀決勝',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 13,
    },
    {
      id: 'simayi',
      name: '司馬懿',
      war: 57,
      int: 96,
      command: 97,
      role: '深謀統軍',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 14,
    },
    {
      id: 'jiaxu',
      name: '賈詡',
      war: 33,
      int: 96,
      command: 70,
      role: '料敵設謀',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 15,
    },
    {
      id: 'caopi',
      name: '曹丕',
      war: 71,
      int: 84,
      command: 80,
      role: '文治開國',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 16,
    },
    {
      id: 'caozhi',
      name: '曹植',
      war: 31,
      int: 90,
      command: 39,
      role: '才高八斗',
      specialty: '內政',
      faction: 'wei',
      portraitIndex: 17,
    },
    {
      id: 'caohong',
      name: '曹洪',
      war: 82,
      int: 55,
      command: 77,
      role: '驍勇護主',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 18,
    },
    {
      id: 'caochun',
      name: '曹純',
      war: 85,
      int: 66,
      command: 86,
      role: '虎豹騎督',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 19,
    },
    {
      id: 'caoxiu',
      name: '曹休',
      war: 81,
      int: 73,
      command: 84,
      role: '千里良駒',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 20,
    },
    {
      id: 'caozhen',
      name: '曹真',
      war: 82,
      int: 75,
      command: 89,
      role: '西陲統軍',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 21,
    },
    {
      id: 'xiahoushang',
      name: '夏侯尚',
      war: 76,
      int: 77,
      command: 82,
      role: '征南督軍',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 22,
    },
    {
      id: 'manchong',
      name: '滿寵',
      war: 59,
      int: 89,
      command: 84,
      role: '堅壁禦敵',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 23,
    },
    {
      id: 'chengyu',
      name: '程昱',
      war: 54,
      int: 94,
      command: 74,
      role: '謀定後動',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 24,
    },
    {
      id: 'xunyou',
      name: '荀攸',
      war: 27,
      int: 96,
      command: 73,
      role: '奇策十二',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 25,
    },
    {
      id: 'chenqun',
      name: '陳群',
      war: 22,
      int: 90,
      command: 36,
      role: '九品賢臣',
      specialty: '內政',
      faction: 'wei',
      portraitIndex: 26,
    },
    {
      id: 'zhongyao',
      name: '鍾繇',
      war: 24,
      int: 87,
      command: 40,
      role: '德望重臣',
      specialty: '內政',
      faction: 'wei',
      portraitIndex: 27,
    },
    {
      id: 'dengai',
      name: '鄧艾',
      war: 83,
      int: 91,
      command: 94,
      role: '奇襲陰平',
      specialty: '統帥',
      faction: 'wei',
      portraitIndex: 28,
    },
    {
      id: 'zhonghui',
      name: '鍾會',
      war: 55,
      int: 94,
      command: 88,
      role: '謀略縱橫',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 29,
    },
    {
      id: 'wangshuang',
      name: '王雙',
      war: 87,
      int: 37,
      command: 66,
      role: '重斧猛將',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 30,
    },
    {
      id: 'wenping',
      name: '文聘',
      war: 85,
      int: 72,
      command: 87,
      role: '江漢磐石',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 31,
    },
    {
      id: 'zangba',
      name: '臧霸',
      war: 80,
      int: 63,
      command: 81,
      role: '泰山宿將',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 32,
    },
    {
      id: 'pangde',
      name: '龐德',
      war: 94,
      int: 69,
      command: 85,
      role: '白馬驍將',
      specialty: '勇將',
      faction: 'wei',
      portraitIndex: 33,
    },
    {
      id: 'simashi',
      name: '司馬師',
      war: 69,
      int: 90,
      command: 87,
      role: '沉毅經略',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 34,
    },
    {
      id: 'simazhao',
      name: '司馬昭',
      war: 62,
      int: 88,
      command: 81,
      role: '持重謀國',
      specialty: '謀士',
      faction: 'wei',
      portraitIndex: 35,
    },
  ],
  shu: [
    {
      id: 'liu',
      name: '劉備',
      war: 78,
      int: 80,
      command: 88,
      role: '仁德之主',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 0,
    },
    {
      id: 'guan',
      name: '關羽',
      war: 98,
      int: 76,
      command: 94,
      role: '萬人之敵',
      specialty: '統帥',
      faction: 'shu',
      portraitIndex: 1,
    },
    {
      id: 'zhang',
      name: '張飛',
      war: 99,
      int: 45,
      command: 88,
      role: '勇冠三軍',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 2,
    },
    {
      id: 'zhuge',
      name: '諸葛亮',
      war: 38,
      int: 99,
      command: 95,
      role: '臥龍軍師',
      specialty: '統帥',
      faction: 'shu',
      portraitIndex: 3,
    },
    {
      id: 'zhaoyun',
      name: '趙雲',
      war: 96,
      int: 81,
      command: 94,
      role: '長槍突陣',
      specialty: '統帥',
      faction: 'shu',
      portraitIndex: 4,
    },
    {
      id: 'huangzhong',
      name: '黃忠',
      war: 93,
      int: 66,
      command: 87,
      role: '神射破敵',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 5,
    },
    {
      id: 'machao',
      name: '馬超',
      war: 95,
      int: 60,
      command: 88,
      role: '鐵騎衝陣',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 6,
    },
    {
      id: 'weiyan',
      name: '魏延',
      war: 91,
      int: 72,
      command: 88,
      role: '奇襲先鋒',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 7,
    },
    {
      id: 'jiangwei',
      name: '姜維',
      war: 88,
      int: 91,
      command: 91,
      role: '文武統軍',
      specialty: '統帥',
      faction: 'shu',
      portraitIndex: 8,
    },
    {
      id: 'pangtong',
      name: '龐統',
      war: 36,
      int: 97,
      command: 82,
      role: '連環奇謀',
      specialty: '謀士',
      faction: 'shu',
      portraitIndex: 9,
    },
    {
      id: 'fazheng',
      name: '法正',
      war: 42,
      int: 95,
      command: 80,
      role: '奇策輔軍',
      specialty: '謀士',
      faction: 'shu',
      portraitIndex: 10,
    },
    {
      id: 'xushu',
      name: '徐庶',
      war: 59,
      int: 94,
      command: 79,
      role: '料敵謀士',
      specialty: '謀士',
      faction: 'shu',
      portraitIndex: 11,
    },
    {
      id: 'maliang',
      name: '馬良',
      war: 32,
      int: 91,
      command: 61,
      role: '內政賢才',
      specialty: '謀士',
      faction: 'shu',
      portraitIndex: 12,
    },
    {
      id: 'guanping',
      name: '關平',
      war: 85,
      int: 66,
      command: 77,
      role: '青龍先鋒',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 13,
    },
    {
      id: 'zhoucang',
      name: '周倉',
      war: 86,
      int: 43,
      command: 63,
      role: '持刀猛士',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 14,
    },
    {
      id: 'madai',
      name: '馬岱',
      war: 86,
      int: 74,
      command: 80,
      role: '穩健副將',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 15,
    },
    {
      id: 'liushan',
      name: '劉禪',
      war: 26,
      int: 58,
      command: 41,
      role: '寬仁守成',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 16,
    },
    {
      id: 'guanxing',
      name: '關興',
      war: 88,
      int: 67,
      command: 78,
      role: '青龍繼志',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 17,
    },
    {
      id: 'zhangbao',
      name: '張苞',
      war: 89,
      int: 53,
      command: 76,
      role: '燕人後繼',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 18,
    },
    {
      id: 'zhangyi',
      name: '張翼',
      war: 77,
      int: 72,
      command: 81,
      role: '南征宿將',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 19,
    },
    {
      id: 'wangping',
      name: '王平',
      war: 77,
      int: 78,
      command: 87,
      role: '無當飛軍',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 20,
    },
    {
      id: 'liaohua',
      name: '廖化',
      war: 77,
      int: 68,
      command: 77,
      role: '歷戰先鋒',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 21,
    },
    {
      id: 'zhangni',
      name: '張嶷',
      war: 76,
      int: 76,
      command: 82,
      role: '安南良將',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 22,
    },
    {
      id: 'wuyi',
      name: '吳懿',
      war: 77,
      int: 71,
      command: 83,
      role: '漢中督軍',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 23,
    },
    {
      id: 'liyan',
      name: '李嚴',
      war: 77,
      int: 82,
      command: 82,
      role: '才幹治軍',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 24,
    },
    {
      id: 'yanyan',
      name: '嚴顏',
      war: 84,
      int: 70,
      command: 81,
      role: '巴蜀老將',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 25,
    },
    {
      id: 'menghuo',
      name: '孟獲',
      war: 90,
      int: 51,
      command: 77,
      role: '南中雄主',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 26,
    },
    {
      id: 'zhurong',
      name: '祝融',
      war: 88,
      int: 59,
      command: 72,
      role: '飛刃逐獵',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 27,
    },
    {
      id: 'huangyueying',
      name: '黃月英',
      war: 44,
      int: 95,
      command: 48,
      role: '巧思善工',
      specialty: '內政',
      faction: 'shu',
      portraitIndex: 28,
    },
    {
      id: 'sunshangxiang',
      name: '孫尚香',
      war: 86,
      int: 70,
      command: 74,
      role: '弓腰姬將',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 29,
    },
    {
      id: 'baosanniang',
      name: '鮑三娘',
      war: 83,
      int: 58,
      command: 67,
      role: '鳳舞戰陣',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 30,
    },
    {
      id: 'guanyinping',
      name: '關銀屏',
      war: 87,
      int: 61,
      command: 72,
      role: '虎女青鋒',
      specialty: '勇將',
      faction: 'shu',
      portraitIndex: 31,
    },
    {
      id: 'mizhu',
      name: '糜竺',
      war: 23,
      int: 85,
      command: 38,
      role: '富商輔漢',
      specialty: '內政',
      faction: 'shu',
      portraitIndex: 32,
    },
    {
      id: 'jianyong',
      name: '簡雍',
      war: 27,
      int: 82,
      command: 34,
      role: '談笑折衝',
      specialty: '內政',
      faction: 'shu',
      portraitIndex: 33,
    },
    {
      id: 'sunqian',
      name: '孫乾',
      war: 26,
      int: 84,
      command: 35,
      role: '辯才安邦',
      specialty: '內政',
      faction: 'shu',
      portraitIndex: 34,
    },
    {
      id: 'feiyi',
      name: '費禕',
      war: 30,
      int: 93,
      command: 74,
      role: '經國濟民',
      specialty: '謀士',
      faction: 'shu',
      portraitIndex: 35,
    },
  ],
  wu: [
    {
      id: 'sun',
      name: '孫權',
      war: 73,
      int: 87,
      command: 88,
      role: '江東之主',
      specialty: '謀士',
      faction: 'wu',
      portraitIndex: 0,
    },
    {
      id: 'zhou',
      name: '周瑜',
      war: 78,
      int: 97,
      command: 97,
      role: '江左風流',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 1,
    },
    {
      id: 'gan',
      name: '甘寧',
      war: 95,
      int: 68,
      command: 87,
      role: '錦帆遊俠',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 2,
    },
    {
      id: 'taishi',
      name: '太史慈',
      war: 96,
      int: 66,
      command: 88,
      role: '忠勇無雙',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 3,
    },
    {
      id: 'luxun',
      name: '陸遜',
      war: 65,
      int: 95,
      command: 96,
      role: '火計統軍',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 4,
    },
    {
      id: 'lumeng',
      name: '呂蒙',
      war: 86,
      int: 87,
      command: 93,
      role: '白衣渡江',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 5,
    },
    {
      id: 'huanggai',
      name: '黃蓋',
      war: 87,
      int: 66,
      command: 85,
      role: '苦肉破敵',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 6,
    },
    {
      id: 'chengpu',
      name: '程普',
      war: 85,
      int: 75,
      command: 88,
      role: '宿將統軍',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 7,
    },
    {
      id: 'handang',
      name: '韓當',
      war: 85,
      int: 64,
      command: 82,
      role: '水戰先鋒',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 8,
    },
    {
      id: 'zhoutai',
      name: '周泰',
      war: 94,
      int: 47,
      command: 79,
      role: '鐵軀護主',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 9,
    },
    {
      id: 'lingtong',
      name: '凌統',
      war: 90,
      int: 66,
      command: 81,
      role: '破圍先鋒',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 10,
    },
    {
      id: 'xusheng',
      name: '徐盛',
      war: 85,
      int: 77,
      command: 86,
      role: '江防築壘',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 11,
    },
    {
      id: 'dingfeng',
      name: '丁奉',
      war: 89,
      int: 71,
      command: 85,
      role: '雪中奮兵',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 12,
    },
    {
      id: 'zhangzhao',
      name: '張昭',
      war: 30,
      int: 94,
      command: 62,
      role: '內政重臣',
      specialty: '謀士',
      faction: 'wu',
      portraitIndex: 13,
    },
    {
      id: 'lusu',
      name: '魯肅',
      war: 52,
      int: 95,
      command: 85,
      role: '聯軍謀士',
      specialty: '謀士',
      faction: 'wu',
      portraitIndex: 14,
    },
    {
      id: 'zhugejin',
      name: '諸葛瑾',
      war: 43,
      int: 91,
      command: 74,
      role: '外交賢臣',
      specialty: '謀士',
      faction: 'wu',
      portraitIndex: 15,
    },
    {
      id: 'sunjian',
      name: '孫堅',
      war: 92,
      int: 77,
      command: 93,
      role: '江東猛虎',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 16,
    },
    {
      id: 'sunce',
      name: '孫策',
      war: 94,
      int: 74,
      command: 94,
      role: '江東小霸',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 17,
    },
    {
      id: 'lukang',
      name: '陸抗',
      war: 71,
      int: 90,
      command: 94,
      role: '社稷之衛',
      specialty: '統帥',
      faction: 'wu',
      portraitIndex: 18,
    },
    {
      id: 'luji',
      name: '陸績',
      war: 20,
      int: 87,
      command: 29,
      role: '博學知理',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 19,
    },
    {
      id: 'lumao',
      name: '陸瑁',
      war: 25,
      int: 85,
      command: 31,
      role: '明理德士',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 20,
    },
    {
      id: 'zhanghong',
      name: '張紘',
      war: 22,
      int: 91,
      command: 43,
      role: '籌策江東',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 21,
    },
    {
      id: 'buzhi',
      name: '步騭',
      war: 36,
      int: 86,
      command: 75,
      role: '經略交州',
      specialty: '謀士',
      faction: 'wu',
      portraitIndex: 22,
    },
    {
      id: 'zhuhuan',
      name: '朱桓',
      war: 87,
      int: 72,
      command: 88,
      role: '奮威將軍',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 23,
    },
    {
      id: 'zhuran',
      name: '朱然',
      war: 81,
      int: 76,
      command: 87,
      role: '堅守江陵',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 24,
    },
    {
      id: 'panzhang',
      name: '潘璋',
      war: 82,
      int: 57,
      command: 76,
      role: '臨陣悍將',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 25,
    },
    {
      id: 'jiangqin',
      name: '蔣欽',
      war: 83,
      int: 63,
      command: 79,
      role: '輕舟突擊',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 26,
    },
    {
      id: 'dongxi',
      name: '董襲',
      war: 87,
      int: 48,
      command: 75,
      role: '破浪先鋒',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 27,
    },
    {
      id: 'chenwu',
      name: '陳武',
      war: 85,
      int: 52,
      command: 72,
      role: '廬江精銳',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 28,
    },
    {
      id: 'lingcao',
      name: '凌操',
      war: 85,
      int: 46,
      command: 73,
      role: '輕身先登',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 29,
    },
    {
      id: 'heqi',
      name: '賀齊',
      war: 82,
      int: 74,
      command: 84,
      role: '綺甲平亂',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 30,
    },
    {
      id: 'sunshao',
      name: '孫韶',
      war: 78,
      int: 73,
      command: 79,
      role: '鎮北良將',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 31,
    },
    {
      id: 'sunhuan',
      name: '孫桓',
      war: 77,
      int: 71,
      command: 80,
      role: '江東儒將',
      specialty: '勇將',
      faction: 'wu',
      portraitIndex: 32,
    },
    {
      id: 'daqiao',
      name: '大喬',
      war: 30,
      int: 86,
      command: 42,
      role: '端雅明慧',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 33,
    },
    {
      id: 'xiaoqiao',
      name: '小喬',
      war: 32,
      int: 86,
      command: 42,
      role: '江南靈秀',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 34,
    },
    {
      id: 'bulianshi',
      name: '步練師',
      war: 24,
      int: 90,
      command: 36,
      role: '柔德輔政',
      specialty: '內政',
      faction: 'wu',
      portraitIndex: 35,
    },
  ],
};
export const ALL_OFFICERS = Object.values(ROSTERS).flat();
